language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.3
  - DJANGO_VERSION=1.4.1
install:
  - pip install -q Django==$DJANGO_VERSION
script: python run_tests.py